from building import *

src = []
cwd = []
CPPDEFINES = [""]

cwd  = GetCurrentDir()
path =  [cwd]

src += ['board.c']
src += ['drv_clk.c']
src += ['drv_iomux.c']
src += ['drv_dmac.c']

# src += ['drv_ov2640.c']

if  GetDepend('BSP_USING_UART'):
    src += ['drv_uart.c']

if  GetDepend('BSP_USING_SMHC'):
    src += ['drv_smhc.c']

if  GetDepend('BSP_USING_TWI'):
    src += ['drv_twi.c']

if  GetDepend('BSP_USING_EMAC'):
    src += ['drv_emac.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES=CPPDEFINES)

Return('group')
