from building import *

src = []
cwd = []
CPPDEFINES = [""]

cwd  = GetCurrentDir()
path =  [cwd]

src += ['board.c']
src += ['drv_clk.c']
src += ['drv_iomux.c']

if  GetDepend('BSP_USING_UART'):
    src += ['drv_uart.c']

if  GetDepend('BSP_USING_SMHC'):
    src += ['drv_smhc.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES=CPPDEFINES)

Return('group')
